permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

general {
    gaps_in      = 5
    gaps_out     = 11
    border_size  = 0
    allow_tearing = false
    layout       = dwindle
}

decoration {
    rounding       = 7
    rounding_power = 4
    active_opacity   = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    shadow {
        enabled      = true
        range        = 7
        render_power = 3
        color        = rgba(0f0f1480)
        color_inactive = rgba(0f0f1440)
    }
    blur {
        enabled          = true
        size             = 3
        passes           = 2
        new_optimizations = true
        vibrancy         = 0.3
        vibrancy_darkness = 0.0
        noise            = 0.012
        contrast         = 1.0
        brightness       = 2
        xray             = false
        special          = false
    }
}

dwindle {
    pseudotile     = true
    preserve_split = true
    smart_split    = false
    smart_resizing = true
}
master { new_status = master }

misc {
    force_default_wallpaper  = 0
    disable_hyprland_logo    = true
    disable_splash_rendering = true
    mouse_move_enables_dpms  = true
    key_press_enables_dpms   = true
    focus_on_activate        = true
    vfr = true
}
